apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.deployment_name }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.backend.app_label }}
  template:
    metadata:
      labels:
        app: {{ .Values.backend.app_label }}
    spec:
      containers:
        - name: {{ .Values.backend.containername }}
          image: {{ .Values.image_repo }}:{{ .Values.backend.imagetag }}
          ports:
            - containerPort: {{ .Values.backend.containerport }}
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: password
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configmap.name }}
                  key: db_url
            - name: SESSION_TIMEOUT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configmap.name }}
                  key: session_timeout
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.service_name }}
spec:
  selector:
    app: {{ .Values.backend.deployment_name }}
  ports:
    - protocol: TCP
      port: {{ .Values.backend.containerport }}
      targetPort: {{ .Values.backend.targetport }}
