apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap_name }}
data:
  db_url: {{ .Values.configmap_dbUrl | quote }}
  session_timeout: {{ .Values.configmap_sessionTimeout | quote }}
  database_name: {{ .Values.configmap_dbName | quote }}
