apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
data:
  db_url: {{ .Values.configmap.dbUrl | quote }}
  session_timeout: {{ .Values.configmap.sessionTimeout | quote }}
  database_name: {{ .Values.configmap.dbName | quote }}
