{{- if .Values.canary.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.canary.deployment_name }}
spec:
  replicas: {{ .Values.frontend.canary.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.frontend.canary.app_label }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.canary.app_label }}
    spec:
      containers:
        - name: {{ .Values.frontend.canary.containername }}
          image: {{ .Values.image_repo }}:{{ .Values.frontend.canary.imagetag }}
          ports:
            - containerPort: {{ .Values.frontend.canary.containerport }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.canary.service_name }}
spec:
  selector:
    app: {{ .Values.frontend.canary.app_label }}
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.canary.containerport }} # Service port
      targetPort: {{ .Values.frontend.canary.targetport }} # Pod port
  type: LoadBalancer # eneable access outside cluster by using loadbalancer
{{- end }}
