apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.frontend.hpa_name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.frontend.deployment_name }}
  minReplicas: {{ .Values.frontend.hpa_minReplicas}}
  maxReplicas: {{ .Values.frontend.hpa_maxReplicas }}
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.backend.hpa_name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.backend.deployment_name }}
  minReplicas: {{ .Values.backend.hpa_minReplicas}}
  maxReplicas: {{ .Values.backend.hpa_maxReplicas }}
