apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.pv.name }}
spec:
  capacity:
    storage: {{ .Values.pv.storage }}
  volumeMode: Filesystem
  accessModes:
    - {{ .Values.pv.accessmode }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  gcePersistentDisk:
    pdName: {{ .Values.pv.diskname }}
    fsType: ext4

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.name }}
spec:
  accessModes:
    - {{ .Values.pvc.accessmode }}
  resources:
    requests:
      storage: {{ .Values.pvc.requeststorage }}
  storageClassName: standard

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mysql.deployment_name }}
spec:
  replicas: {{ .Values.mysql.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.mysql.app_label }}
  template:
    metadata:
      labels:
        app: {{ .Values.mysql.app_label }}
    spec:
      containers:
        - name: {{ .Values.mysql.containername }}
          image: {{ .Values.image_repo }}:{{ .Values.mysql.imagetag }}
          ports:
            - containerPort: {{ .Values.mysql.containerport }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: password
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configmap.name }}
                  key: database_name
          volumeMounts:
            - name: {{ .Values.volume.name }}
              mountPath: {{ .Values.volume.path }}
      volumes:
        - name: {{ .Values.volume.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.pvc.name }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.servie_name }}
spec:
  selector:
    app: {{ .Values.mysql.app_label }}
  ports:
    - protocol: TCP
      port: {{ .Values.mysql.containerport }}
      targetPort: {{ .Values.mysql.targetport }}
  type: ClusterIP
