apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.pv_name }}
spec:
  capacity:
    storage: {{ .Values.pv_storage }}
  volumeMode: Filesystem
  accessModes:
    - {{ .Values.pv_accessmode }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  gcePersistentDisk:
    pdName: {{ .Values.pv_diskname }}
    fsType: ext4

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc_name }}
spec:
  accessModes:
    - {{ .Values.pvc_accessmode }}
  resources:
    requests:
      storage: {{ .Values.pvc_requeststorage }}
  storageClassName: standard

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mysql_deployment_name }}
spec:
  replicas: {{ .Values.mysql_replicas }}
  selector:
    matchLabels:
      app: {{ .Values.mysql_app_label }}
  template:
    metadata:
      labels:
        app: {{ .Values.mysql_app_label }}
    spec:
      containers:
        - name: {{ .Values.mysql_containername }}
          image: {{ .Values.image_repo }}:{{ .Values.mysql_imagetag }}
          ports:
            - containerPort: {{ .Values.mysql_containerport }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret_name }}
                  key: password
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configmap_name }}
                  key: database_name
          volumeMounts:
            - name: {{ .Values.volume_name }}
              mountPath: {{ .Values.volume_path }}
      volumes:
        - name: {{ .Values.volume_name }}
          persistentVolumeClaim:
            claimName: {{ .Values.pvc_name }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql_servie_name }}
spec:
  selector:
    app: {{ .Values.mysql_app_label }}
  ports:
    - protocol: TCP
      port: {{ .Values.mysql_containerport }}
      targetPort: {{ .Values.mysql_targetport }}
  type: ClusterIP
