apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: observer-role-binding
  namespace: default
subjects:
- kind: User
  name: "your-username"
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: observer
  apiGroup: rbac.authorization.k8s.io