apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      # for svc
      labels:
        app: backend
    spec:
      containers:
      - name: backend-container
        image: "ivywr/p3sc-project:backendv0.0.3"
        # imagePullPolicy: Always
        ports:
        - containerPort: 8080
          env:
            - name: MYSQL_PORT
              value: '3306'
            - name: MYSQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysqlsecret
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysqlsecret
                  key: password